### ISSUE TITLE
【importError】

### ISSUE THREAD

**Issue by WinnixShih** [VVVICTORZHOU/pymeili_resource#1]
Hello engineer, today I tried to import the pymeili version 1.0.4, and this occurs, please help me, I need this for helping me finish the HW
Thx!!

```bash
Traceback (most recent call last):
  File "c:\Users\william\Desktop\vs_code\Python\meil_test.py", line 1, in <module>
    from meil_test import beautifyplot as bp
  File "c:\Users\william\Desktop\vs_code\Python\meil_test.py", line 1, in <module>
    from meil_test import beautifyplot as bp
ImportError: cannot import name 'beautifyplot' from partially initialized module 'meil_test' (most likely due to a circular import) (c:\Users\william\Desktop\vs_code\Python\meil_test.py)
```

**Comment by VVVICTORZHOU** [comment]
Hi user, try to import the package in the following code instead
```python
from pymeili import beautifyplot as bp
```
Note that the package name is `pymeili`, not `meil_test`.

**Comment by WinnixShih** [comment]
ohwww, silly me, thank you very much!!
